services:
    web:
        build: './build/php/'
        ports:
            - "8002:80"
        volumes:
            - .:/var/www/ws_places
        links:
            - db:db
    db:
        build: './build/mysql/'
        volumes:
            - ~/.docker/mysql:/var/lib/mysql
        ports:
            - "3022:3306"
        environment:
            - MYSQL_ROOT_PASSWORD=example
    myadmin:
        image: phpmyadmin/phpmyadmin
        ports:
            - "8072:80"
        links:
            - db:db

volumes:
###> doctrine/doctrine-bundle ###
  database_data:
###< doctrine/doctrine-bundle ###
